// <auto-generated />
using System;
using Bmerketo.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bmerketo.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230526122404_Date")]
    partial class Date
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bmerketo.Models.Entities.CategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "new"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "featured"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "popular"
                        });
                });

            modelBuilder.Entity("Bmerketo.Models.Entities.ContactFormEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContactForms");
                });

            modelBuilder.Entity("Bmerketo.Models.Entities.ProductCategoryEntity", b =>
                {
                    b.Property<string>("ArticleNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("ArticleNumber", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            ArticleNumber = "1",
                            CategoryId = 2
                        },
                        new
                        {
                            ArticleNumber = "2",
                            CategoryId = 1
                        },
                        new
                        {
                            ArticleNumber = "3",
                            CategoryId = 2
                        },
                        new
                        {
                            ArticleNumber = "4",
                            CategoryId = 2
                        },
                        new
                        {
                            ArticleNumber = "5",
                            CategoryId = 1
                        },
                        new
                        {
                            ArticleNumber = "5",
                            CategoryId = 3
                        },
                        new
                        {
                            ArticleNumber = "6",
                            CategoryId = 2
                        },
                        new
                        {
                            ArticleNumber = "6",
                            CategoryId = 3
                        },
                        new
                        {
                            ArticleNumber = "7",
                            CategoryId = 2
                        },
                        new
                        {
                            ArticleNumber = "7",
                            CategoryId = 3
                        },
                        new
                        {
                            ArticleNumber = "8",
                            CategoryId = 1
                        },
                        new
                        {
                            ArticleNumber = "8",
                            CategoryId = 3
                        },
                        new
                        {
                            ArticleNumber = "9",
                            CategoryId = 2
                        },
                        new
                        {
                            ArticleNumber = "9",
                            CategoryId = 3
                        },
                        new
                        {
                            ArticleNumber = "10",
                            CategoryId = 1
                        },
                        new
                        {
                            ArticleNumber = "10",
                            CategoryId = 2
                        },
                        new
                        {
                            ArticleNumber = "10",
                            CategoryId = 3
                        },
                        new
                        {
                            ArticleNumber = "11",
                            CategoryId = 1
                        },
                        new
                        {
                            ArticleNumber = "11",
                            CategoryId = 3
                        },
                        new
                        {
                            ArticleNumber = "12",
                            CategoryId = 1
                        },
                        new
                        {
                            ArticleNumber = "12",
                            CategoryId = 3
                        },
                        new
                        {
                            ArticleNumber = "13",
                            CategoryId = 1
                        },
                        new
                        {
                            ArticleNumber = "13",
                            CategoryId = 3
                        },
                        new
                        {
                            ArticleNumber = "14",
                            CategoryId = 2
                        },
                        new
                        {
                            ArticleNumber = "14",
                            CategoryId = 3
                        },
                        new
                        {
                            ArticleNumber = "14",
                            CategoryId = 1
                        },
                        new
                        {
                            ArticleNumber = "15",
                            CategoryId = 3
                        },
                        new
                        {
                            ArticleNumber = "16",
                            CategoryId = 1
                        },
                        new
                        {
                            ArticleNumber = "17",
                            CategoryId = 1
                        },
                        new
                        {
                            ArticleNumber = "18",
                            CategoryId = 2
                        },
                        new
                        {
                            ArticleNumber = "19",
                            CategoryId = 1
                        },
                        new
                        {
                            ArticleNumber = "20",
                            CategoryId = 2
                        });
                });

            modelBuilder.Entity("Bmerketo.Models.Entities.ProductEntity", b =>
                {
                    b.Property<string>("ArticleNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ingress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArticleNumber");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ArticleNumber = "1",
                            Created = new DateTime(2023, 5, 26, 12, 24, 4, 745, DateTimeKind.Utc).AddTicks(9473),
                            Description = "Designed for hiking trips in the mountains, the Verdant Haven tent provides a spacious and well-ventilated retreat. Unwind amidst the lush greenery of the mountains with this tent from Bmerketo. Its generous interior space offers ample room for rest and storage, ensuring a comfortable and organized adventure. The tent's durable materials and sturdy construction withstand rugged terrains, while the vibrant green color blends harmoniously with the surrounding landscape, making it an eco-conscious choice for nature enthusiasts.",
                            ImageUrl = "1_tent.png",
                            Ingress = "Experience nature in full bloom with the Verdant Haven tent.",
                            Price = 1999m,
                            Title = "Verdant Haven"
                        },
                        new
                        {
                            ArticleNumber = "2",
                            Created = new DateTime(2023, 5, 26, 12, 24, 4, 745, DateTimeKind.Utc).AddTicks(9480),
                            Description = "Immerse yourself in the serene beauty of the mountains with the Forest Oasis tent from Bmerketo. Crafted with high-quality materials, this tent offers a perfect balance of durability and comfort. Its green color palette blends seamlessly with the natural surroundings, providing a peaceful and harmonious retreat. With ample space and thoughtful design, the Forest Oasis ensures a rejuvenating experience for hikers venturing into the mountains.",
                            ImageUrl = "2_tent.png",
                            Ingress = "Step into a tranquil forest oasis with this green hiking tent.",
                            Price = 1899m,
                            Title = "Forest Oasis"
                        },
                        new
                        {
                            ArticleNumber = "3",
                            Created = new DateTime(2023, 5, 26, 12, 24, 4, 745, DateTimeKind.Utc).AddTicks(9482),
                            Description = "The Evergreen Summit tent is tailored for adventurers seeking a seamless connection with the mountains. Its green exterior echoes the perpetual vibrancy of nature, reflecting your passion for exploration. This tent combines functionality and style, providing a comfortable shelter that withstands the challenges of the wilderness. With spacious interiors and reliable weather resistance, the Evergreen Summit becomes your trusted companion on every hiking expedition.",
                            ImageUrl = "3_tent.png",
                            Ingress = "Conquer new heights while embracing the everlasting beauty of nature with the Evergreen Summit tent.",
                            Price = 1799m,
                            Title = "Evergreen Summit"
                        },
                        new
                        {
                            ArticleNumber = "4",
                            Created = new DateTime(2023, 5, 26, 12, 24, 4, 745, DateTimeKind.Utc).AddTicks(9483),
                            Description = "Embrace the serenity of the mountains with the Mountain Moss tent by Bmerketo. Its green color scheme and earthy tones create a seamless fusion with the surrounding environment. Designed for hikers who value a lightweight and compact shelter, this tent offers exceptional portability without compromising on comfort and protection. Let the Mountain Moss be your hidden sanctuary amidst the grandeur of nature.",
                            ImageUrl = "4_tent.png",
                            Ingress = "Blend into the mountain landscape with the natural hues of the Mountain Moss tent.",
                            Price = 1699m,
                            Title = "Mountain Moss"
                        },
                        new
                        {
                            ArticleNumber = "5",
                            Created = new DateTime(2023, 5, 26, 12, 24, 4, 745, DateTimeKind.Utc).AddTicks(9484),
                            Description = "The Emerald Explorer tent is tailor-made for intrepid adventurers who seek to uncover the secrets of the mountains. Its vibrant green shade symbolizes vitality and curiosity. Crafted with rugged materials and reinforced seams, this tent ensures durability and resilience against the elements. The thoughtfully designed interior provides ample space for comfortable rest and gear storage, making it an essential companion for every hiking journey.",
                            ImageUrl = "5_tent.png",
                            Ingress = "Embark on an expedition of discovery with the Emerald Explorer tent.",
                            Price = 1599m,
                            Title = "Emerald Explorer"
                        },
                        new
                        {
                            ArticleNumber = "6",
                            Created = new DateTime(2023, 5, 26, 12, 24, 4, 745, DateTimeKind.Utc).AddTicks(9508),
                            Description = "Escape the hustle and bustle of everyday life and find your sanctuary in the mountains with the Wildwood Retreat tent. Its green exterior blends seamlessly with the forested landscapes, creating an immersive experience in nature. This tent combines practicality and comfort, featuring easy setup, sturdy construction, and optimal ventilation. Whether you're embarking on a solo adventure or camping with friends, the Wildwood Retreat offers a tranquil haven for your outdoor pursuits.",
                            ImageUrl = "6_tent.png",
                            Ingress = "Find solace in the heart of the wilderness with the Wildwood Retreat tent.",
                            Price = 1499m,
                            Title = "Wildwood Retreat"
                        },
                        new
                        {
                            ArticleNumber = "7",
                            Created = new DateTime(2023, 5, 26, 12, 24, 4, 745, DateTimeKind.Utc).AddTicks(9509),
                            Description = "Let the Sunny Ascent tent be your beacon of warmth and positivity during mountain hikes. Crafted with durability in mind, this tent offers reliable protection against the elements. Its user-friendly setup ensures hassle-free assembly, while the ample space inside allows for comfortable rest and gear storage. The bright yellow color not only lifts your spirits but also ensures high visibility, making it an ideal choice for safety-conscious adventurers.",
                            ImageUrl = "7_tent.png",
                            Ingress = "Embrace sunny days on your mountain expeditions with the Sunny Ascent tent.",
                            Price = 1899m,
                            Title = "Sunny Ascent"
                        },
                        new
                        {
                            ArticleNumber = "8",
                            Created = new DateTime(2023, 5, 26, 12, 24, 4, 745, DateTimeKind.Utc).AddTicks(9510),
                            Description = "The Crimson Summit tent is your reliable companion for thrilling mountain expeditions. Its vibrant red exterior reflects your passion for adventure and determination to reach new summits. Built with rugged materials and reinforced seams, this tent offers exceptional durability and weather resistance. Inside, you'll find a comfortable sanctuary to rest and rejuvenate, ensuring you're ready to face the challenges of the mountains with renewed vigor.",
                            ImageUrl = "8_tent.png",
                            Ingress = "Conquer new heights with the confidence and adventure of the Crimson Summit tent.",
                            Price = 1799m,
                            Title = "Crimson Summit"
                        },
                        new
                        {
                            ArticleNumber = "9",
                            Created = new DateTime(2023, 5, 26, 12, 24, 4, 745, DateTimeKind.Utc).AddTicks(9512),
                            Description = "Fuel your adventurous spirit with the Fiery Ascent tent from Bmerketo. Its bold red color ignites your passion for exploration, while its robust construction guarantees reliability and protection. This tent is designed to withstand various weather conditions, offering you a safe and comfortable retreat amidst the grandeur of the mountains. Unleash your inner adventurer and conquer new heights with the Fiery Ascent as your trusty companion.",
                            ImageUrl = "9_tent.png",
                            Ingress = "Embark on a fiery ascent into the mountains with this red hiking tent.",
                            Price = 1699m,
                            Title = "Fiery Ascent"
                        },
                        new
                        {
                            ArticleNumber = "10",
                            Created = new DateTime(2023, 5, 26, 12, 24, 4, 745, DateTimeKind.Utc).AddTicks(9513),
                            Description = "Prepare to blaze new trails with the Trailblazer tent from Bmerketo. This lightweight and compact tent is crafted for hikers who seek agility without compromising on durability. Its orange hue symbolizes the spirit of exploration, and its waterproof construction ensures you stay protected in changing weather conditions. With easy setup and ample interior space, the Trailblazer is your reliable shelter on the mountains, allowing you to focus on the thrill of the journey.",
                            ImageUrl = "10_tent.png",
                            Ingress = "Ignite your path with the Blaze Trailblazer tent, designed for intrepid explorers.",
                            Price = 1799m,
                            Title = "Blaze Trailblazer"
                        },
                        new
                        {
                            ArticleNumber = "11",
                            Created = new DateTime(2023, 5, 26, 12, 24, 4, 745, DateTimeKind.Utc).AddTicks(9514),
                            Description = "The Citrus Blaze tent infuses your outdoor adventures with a burst of vibrant energy. Its vivid orange color radiates enthusiasm and adds a touch of excitement to your mountain escapades. Crafted with durability and functionality in mind, this tent provides reliable protection and comfort. Whether you're embarking on a solo expedition or camping with friends, the Citrus Blaze ensures a cozy and secure shelter, allowing you to fully embrace the wonders of nature.",
                            ImageUrl = "11_tent.png",
                            Ingress = "Immerse yourself in the invigorating aura of the Citrus Blaze tent.",
                            Price = 1699m,
                            Title = "Citrus Blaze"
                        },
                        new
                        {
                            ArticleNumber = "12",
                            Created = new DateTime(2023, 5, 26, 12, 24, 4, 745, DateTimeKind.Utc).AddTicks(9515),
                            Description = "Immerse yourself in the soothing serenity of the Azure Crest tent. Designed for hikers seeking peace and relaxation, its elegant blue color evokes the beauty of clear skies and pristine waters. Crafted with meticulous attention to detail, this tent offers excellent ventilation, ensuring a comfortable and refreshing sleep after a day of mountain exploration. Its durable materials and sturdy structure provide reliable protection, allowing you to experience the true essence of nature without compromising on comfort.",
                            ImageUrl = "12_tent.png",
                            Ingress = "Discover tranquility amidst the mountains with the Azure Crest tent.",
                            Price = 1699m,
                            Title = "Azure Crest"
                        },
                        new
                        {
                            ArticleNumber = "13",
                            Created = new DateTime(2023, 5, 26, 12, 24, 4, 745, DateTimeKind.Utc).AddTicks(9516),
                            Description = "The Sapphire Summit tent is designed to accompany you on your mountain journeys with style and reliability. Its captivating blue color reflects the majesty of glacial lakes and towering peaks. Crafted with high-quality materials, this tent offers optimal weather protection and durability. Its spacious interior provides ample room for rest and gear storage, while the thoughtfully designed ventilation system ensures a comfortable and refreshing experience amidst the breathtaking beauty of the mountains.",
                            ImageUrl = "13_tent.png",
                            Ingress = "Reach new heights with the Sapphire Summit tent, your gateway to alpine wonders.",
                            Price = 1599m,
                            Title = "Sapphire Summit"
                        },
                        new
                        {
                            ArticleNumber = "14",
                            Created = new DateTime(2023, 5, 26, 12, 24, 4, 745, DateTimeKind.Utc).AddTicks(9519),
                            Description = "Step into the ethereal world of mountain peaks with the Alpine Mist tent. Inspired by the breathtaking beauty of alpine landscapes, its blue and white color scheme captures the essence of majestic snow-capped summits. Crafted with premium materials, this tent ensures durability and protection during your hiking adventures. Its spacious interior and efficient ventilation create a cozy haven where you can recharge and reflect on the awe-inspiring sights surrounding you.",
                            ImageUrl = "14_tent.png",
                            Ingress = "Experience the enchantment of alpine landscapes with the Alpine Mist tent.",
                            Price = 1799m,
                            Title = "Alpine Mist"
                        },
                        new
                        {
                            ArticleNumber = "15",
                            Created = new DateTime(2023, 5, 26, 12, 24, 4, 745, DateTimeKind.Utc).AddTicks(9520),
                            Description = "Venture into the unknown with the Shadow Seeker tent from Bmerketo. Its sleek black exterior symbolizes the enigmatic beauty of the mountains, while its robust construction provides reliable shelter against harsh elements. Designed for intrepid explorers, this tent offers ample space to rest and store your gear, ensuring a comfortable and organized journey. Let the Shadow Seeker be your steadfast companion as you navigate the mysteries of the wilderness.",
                            ImageUrl = "15_tent.png",
                            Ingress = "Embrace the mystery and allure of the mountains with the Shadow Seeker tent.",
                            Price = 1899m,
                            Title = "Shadow Seeker"
                        },
                        new
                        {
                            ArticleNumber = "16",
                            Created = new DateTime(2023, 5, 26, 12, 24, 4, 745, DateTimeKind.Utc).AddTicks(9521),
                            Description = "Reach the pinnacle of mountaineering experiences with the Frost Peak tent. Crafted to withstand challenging terrains and varying weather conditions, this tent is a reliable shelter for adventurers seeking both comfort and durability. Its white exterior mirrors the beauty of snow-covered peaks, while the spacious interior offers a peaceful sanctuary for rest and rejuvenation. Embark on your mountain expeditions with the confidence that the Frost Peak will be your steadfast companion.",
                            ImageUrl = "16_tent.png",
                            Ingress = "Ascend to the heights with the Frost Peak tent.",
                            Price = 1699m,
                            Title = "Frost Peak"
                        },
                        new
                        {
                            ArticleNumber = "17",
                            Created = new DateTime(2023, 5, 26, 12, 24, 4, 745, DateTimeKind.Utc).AddTicks(9522),
                            Description = "Immerse yourself in the untamed beauty of nature with the Earthy Explorer tent. Crafted with outdoor enthusiasts in mind, its earthy brown color represents a strong connection to the wilderness. This tent embraces the rugged aesthetics of the mountains while providing a sturdy and reliable shelter. With its spacious interior and thoughtful design, the Earthy Explorer invites you to embark on unforgettable hiking trips, forging a deeper bond with the natural world around you.",
                            ImageUrl = "17_tent.png",
                            Ingress = "Connect with the natural world on your mountain journeys with the Earthy Explorer tent.",
                            Price = 1599m,
                            Title = "Earthy Explorer"
                        },
                        new
                        {
                            ArticleNumber = "18",
                            Created = new DateTime(2023, 5, 26, 12, 24, 4, 745, DateTimeKind.Utc).AddTicks(9523),
                            Description = "The Coastal Breeze tent in soothing blue hue invites you to experience the tranquility of the great outdoors. Crafted for adventurers who seek solace near water bodies, this tent combines functionality and style. Its lightweight design ensures easy transportation, while the robust materials and reliable construction offer protection against the elements. With ample space to rest and rejuvenate, the Coastal Breeze tent becomes your serene sanctuary as you embark on coastal hikes and lakeside explorations.",
                            ImageUrl = "18_tent.png",
                            Ingress = "Immerse yourself in the calming embrace of nature with the Coastal Breeze tent.",
                            Price = 1699m,
                            Title = "Coastal Breeze"
                        },
                        new
                        {
                            ArticleNumber = "19",
                            Created = new DateTime(2023, 5, 26, 12, 24, 4, 745, DateTimeKind.Utc).AddTicks(9524),
                            Description = "The Snowy Summit tent in pure white stands as a testament to your quest for high-altitude escapades. Designed for mountaineers and alpine enthusiasts, this tent is built to withstand extreme conditions while providing a comfortable and secure shelter. Its durable materials and sturdy structure ensure reliable protection, while the efficient ventilation system keeps you fresh and invigorated amidst the breathtaking beauty of snow-covered peaks. Conquer the highest summits with the Snowy Summit as your trusted companion.",
                            ImageUrl = "19_tent.png",
                            Ingress = "Reach the pinnacle of alpine adventures with the Snowy Summit tent.",
                            Price = 1599m,
                            Title = "Snowy Summit"
                        },
                        new
                        {
                            ArticleNumber = "20",
                            Created = new DateTime(2023, 5, 26, 12, 24, 4, 745, DateTimeKind.Utc).AddTicks(9525),
                            Description = "The Terra Trailblazer tent in earthy brown color is your ultimate companion for off-the-beaten-path adventures. Crafted with durability and versatility in mind, this tent is designed to withstand the toughest terrains and harshest weather conditions. Its sturdy construction ensures reliable protection, while the spacious interior offers a comfortable retreat after a day of exploring the untamed wilderness. Experience the thrill of venturing into uncharted territories with the Terra Trailblazer as your reliable shelter.",
                            ImageUrl = "20_tent.png",
                            Ingress = "Blaze your own trail through the rugged wilderness with the Terra Trailblazer tent.",
                            Price = 1799m,
                            Title = "Terra Trailblazer"
                        });
                });

            modelBuilder.Entity("Bmerketo.Models.Entities.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "514aa140-ea94-456b-a2b9-ec192333a695",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0164baa1-9ad5-43cf-a790-f037f47acf28",
                            Email = "admin@domain.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@DOMAIN.COM",
                            NormalizedUserName = "ADMIN@DOMAIN.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENfFhHG0SMS7QcWqXlbaWjgVL5dO7LSIoBSajiBeghR9+3/UbD+D2yds6vBUM37uig==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e46b422b-5290-4669-a9bb-55aa6e18132d",
                            TwoFactorEnabled = false,
                            UserName = "admin@domain.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "d685a377-733b-4bec-9d62-9025feb9e29b",
                            ConcurrencyStamp = "2738d2d7-866e-4cce-9f93-0113f8f11b89",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "492c2320-c10f-4f1e-a29c-faedb0f30ee3",
                            ConcurrencyStamp = "4d7cd9a2-3c90-41ab-8c66-d59f5be1851c",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "514aa140-ea94-456b-a2b9-ec192333a695",
                            RoleId = "d685a377-733b-4bec-9d62-9025feb9e29b"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Bmerketo.Models.Entities.ProductCategoryEntity", b =>
                {
                    b.HasOne("Bmerketo.Models.Entities.ProductEntity", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ArticleNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bmerketo.Models.Entities.CategoryEntity", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Bmerketo.Models.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Bmerketo.Models.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bmerketo.Models.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Bmerketo.Models.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bmerketo.Models.Entities.CategoryEntity", b =>
                {
                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("Bmerketo.Models.Entities.ProductEntity", b =>
                {
                    b.Navigation("ProductCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
